config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'photos/index'

  get 'photos/new'

  get 'photos/create'

  get 'photos/edit'

  get 'photos/update'

  resources :photos do
    resources :comments
    member  do
      put "like", to: "photos#upvote"
    end
  end
  
  get 'active/photos/:photo_id/comments/:id', to: 'comments#active', as: 'comments_active'
  
  get 'deactive/photos/:photo_id/comments/:id', to: 'comments#deactive', as: 'comments_deactive'
  
  namespace :admin do
    resources :photos, :comments
  end
  
  get 'tag/:tag', to: 'photos#index', as: 'tag'
  
  root 'photos#index'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :photo
  belongs_to :user
  validates :content, presence: true
  scope :active, -> {where status: 1}
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  acts_as_votable
  attr_accessor :status
  
  has_attached_file :photo, styles: {medium: "300x300>", thumb: "100x100>"}, default_url: "/images/:styles/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  validates :title, presence: true
  
  has_many :comments
  belongs_to :user
  has_many :taggings
  has_many :tags, :through => :taggings
  
  def tag_list=(labels)
    self.tags = labels.split(',').map do |label|
      Tag.where(label: label.gsub(/\s+/, '').strip).first_or_create!
    end
  end
  
  def tag_list
    self.tags.map(&:label).join(', ')
  end
  
  def self.tag_with(name)
    Tag.find_by_label!(name).photos
  end
  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :photos, :through => :taggings

  
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :photo
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :comments
  has_many :photos
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < Admin::ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @photo  = Photo.find(comment_params[:photo_id])
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to @photo, notice: "Comment successfully !"
    else
      redirect_to @photo, :flash => { :error => "Comment is error !" }
    end
  end
  
  def active
    @comment = Comment.find(params[:id])
    @comment.status = 1;
    if @comment.save
      redirect_to edit_photo_path(params[:photo_id]), notice: "Comment active successfully !"
    else
      redirect_to edit_photo_path(params[:photo_id]), :flash => { :error => "Comment active error !" }
    end 
  end
  
  def deactive
    @comment = Comment.find(params[:id])
    @comment.status = 0;
    if @comment.save
      redirect_to edit_photo_path(params[:photo_id]), notice: "Comment deactive successfully !"
    else
      redirect_to edit_photo_path(params[:photo_id]), :flash => { :error => "Comment active error !" }
    end 
  end
  
  private
  def comment_params
    params.require(:comment).permit(:content, :photo_id);
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :find_photo, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    if(params[:tag])
      @photos = Photo.tag_with(params[:tag])
    else
      @photos = Photo.all.order("created_at DESC")
    end
  end

  def new
    @photo = current_user.photos.build
  end

  def create
    @photo = current_user.photos.build(photo_params)
    if @photo.save
      redirect_to @photo, notice: "Create Successfully !"
    else
      render 'new'
    end
  end
  
  def show
    @comment = Comment.new(:photo => @photo)
  end

  def edit
  end

  def update
    if @photo.update(photo_params)
      redirect_to @photo, notice: "Update successfully !"
    else
      render 'edit'
    end
  end
  
  def destroy
    @photo.destroy
    redirect_to root_path
  end
  
  def upvote
    @photo.upvote_by current_user
    redirect_to :back
  end
  
  private
  
  def find_photo
    @photo = Photo.find(params[:id])
  end
  
  def photo_params
    params.require(:photo).permit(:title, :description, :photo, :tag_list)
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/photos_helper.rb
module Admin::PhotosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
  def is_current_user_photo(photo)
    current_user.id == photo.user_id
  end
  
  def tag_links(tags)
    tags.split(',').map{|tag| link_to '#' + tag.strip, tag_path(tag.strip) }.join(' ')
  end
end

app/views/admin/photos/index.html.erb
admin photo

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Ducgramm
    = stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top.navbar-ducgram-fixed
      .container-fluid
        .navbar-header
          = link_to "DucGramm", root_path, class: 'navbar-brand'
        %ul.nav.navbar-nav
          %li
            - if user_signed_in?
              = link_to "Gramm It!", new_photo_path
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li
              = link_to raw("<span class='glyphicon glyphicon-log-out'></span>Logout"), destroy_user_session_path, method: :delete
          - else
            %li
              %a{:href=>new_user_registration_path}
                %span.glyphicon.glyphicon-user 
                Sign Up
            %li
              %a{:href=> new_user_session_path }
                %span.glyphicon.glyphicon-log-in
                Login
              
            
    .container.main
      - flash.each do |key, value|
        = content_tag  :div, value, class: "alert alert-#{key}"
      = yield
    
    

app/views/partials/photos/_comment.html.haml
%ul.comments
  - @photo.comments.active.each do |c|
    %li
      %small.date
        = c.created_at.strftime("%c")
      .comment-content
        - unless c.user.nil?
          %small.account
            = c.user.email
        - else
          %small.account Guest
        = c.content

app/views/partials/photos/_comment_form.html.haml
= form_for ([@photo, @comment]) do |f|
  .form-group
    = f.text_area  :content, class: 'form-control'
    = f.hidden_field :photo_id
  .pull-right
    = f.submit  "Send", class:"btn btn-primary"
    

app/views/partials/photos/_comment_list.html.haml
.list-group
  - @photo.comments.each do |c|
    - if c.status == 1
      = link_to c.content, comments_deactive_path(@photo, c), class:'list-group-item active'
    - else
      = link_to c.content, comments_active_path(@photo, c), class:'list-group-item'

app/views/partials/photos/_form.html.haml
= form_for @photo, html: { multipart: true } do |p|
  .form-group
    = p.label :title
    = p.text_field :title, class: 'form-control'
  .form_group
    = p.label :description
    = p.text_area :description, class: 'form-control'
  .form_group
    = p.label :photo
    = p.file_field :photo
    - if @photo.photo.exists?
      = image_tag @photo.photo.url(:thumb)
  .form-group
    = p.label :tag_list
    = p.text_field :tag_list, 'data-role' => "tagsinput", class: 'form-control'
  .pull-right.btn-d-group
    = p.submit class: 'btn btn-primary'
    = link_to "Cancel", @photo, class: 'btn btn-default'

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/edit.html.haml
.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h4 Edit Photo
      .panel-body
        = render 'partials/photos/form'
  .row
    .panel.panel-default
      .panel-heading
        %h4 Comment
      .panel-body
        = render 'partials/photos/comment_list'
  

app/views/photos/index.html.haml
.col-md-6.col-md-offset-3
  - @photos.each do |photo|
    .box.panel.panel-default
      .panel-body
        = image_tag photo.photo.url, class: "img-responsive"
        .tags
          = raw tag_links(photo.tag_list)
        %h4
          = link_to photo.title, photo
        %small
          = photo.description

app/views/photos/new.html.haml
.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h4 New Photo
      .panel-body
        =render 'partials/photos/form'
  

app/views/photos/show.html.haml
.col-md-8.col-md-offset-2
  - flash.each do |name, msg|
    = content_tag  :div, msg, class: 'alert alert-info'
  .row
    .panel.panel-default
      .panel-heading
        %h4
          = @photo.title
      .panel-body
        = image_tag @photo.photo.url, class: 'img-responsive'
        .small
          = @photo.description
        .tag
          = raw tag_links(@photo.tag_list)
      .panel-footer
        .row
          .pull-right
            .btn-group.btn-group-fix
              = link_to like_photo_path, method: "put", class: "btn btn-default" do
                %span.glyphicon.glyphicon-thumbs-up
                = @photo.get_upvotes.size
              - if user_signed_in? && is_current_user_photo(@photo)
                = link_to "Edit", edit_photo_path, class: 'btn btn-primary'
                = link_to "Remove", photo_path, method: :delete, data: { confirm: "Are you sure ?" }, class: "btn btn-danger"
              = link_to "Back", root_path, class: 'btn btn-default'
  - if user_signed_in?
    .row
      .panel.panel-default
        .panel-heading
          %h4
            Comment
        .panel-body
          = render 'partials/photos/comment'
          = render 'partials/photos/comment_form'

app/views/photos/update.html.erb
<h1>Photos#update</h1>
<p>Find me in app/views/photos/update.html.erb</p>